### ISSUE TITLE
Import data improvements

### ISSUE THREAD

**Issue by HanXHX** [HanXHX/ansible-mysql#2]
In this role, i use some hack to import data with percona-toolkit.

I need help to find a way to import data:
- add mysqldump
- xtrabackup over ssh... i need to rewrite this code, i don't like it

**Comment by maximumG** [comment]
I'm also looking for a way to automate data import when bootstraping a new galera cluster, using mariabackup and with the following method:

1. Bootstrap the first node (galera_new_cluster)
2. Import data on the first node
3. Reboot the other cluster members one by one in order to use SST for row replication

Inspired from https://severalnines.com/database-blog/guide-mysql-galera-cluster-restoration-using-mysqldump

In term of implementation, I was thinking of a dedicated yaml tasks that could be easily imported

* in _main.yaml_ for a standalone mariadb server
* in _replication/master.yaml_ for a master-slave async replication
* in _galera/bootstrap.yml_ for a galera cluster

**Comment by HanXHX** [comment]
Hi,

This issue was about async replication (5 years old!) to setup a new slave. 

The main problem is about which method to restore data . Each people/companies uses different methods: mysqldump :baby:, mydumper, LVM/ZFS snapshots, mariabackup... etc.

I don't like this code [import_data.yml](https://github.com/HanXHX/ansible-mysql/blob/master/tasks/replication/slave/import_data.yml). It works well with vagrant box but it's **not production ready**.

This role must not manage each case. I think the best way is to manage with an external playbook.

Ansistrano role uses [hooks](https://github.com/ansistrano/deploy#hooks-custom-tasks). I think it can be an interesting way.

Something like:

- before_bootstrap
- after_bootstrap
- before_start_node
- after_start_node

EM
